name: safasoft_mrz_scanner_flutter_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler:
  lottie: ^2.6.0
  google_mlkit_text_recognition: ^0.4.0
  hive:
  hive_flutter:
  bloc:
  flutter_bloc:
  image_picker: ^1.0.2
  mrz_scanner: ^0.0.1+3
  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator:
  build_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
